added majority of intended features

diff --git a/frankTriples b/frankTriples
--- a/frankTriples
+++ b/frankTriples
@@ -9,43 +9,102 @@ command -v curl >/dev/null 2>&1 || { echo >&2 "Please install curl first"; exit 
 # Usage info
 show_help() {
 cat << EOF
-Usage: ${0##*/} [-hv] [--graph graph] [FILE]...
-Do stuff with FILE and write the result to standard output. With no FILE
-or when FILE is -, read standard input.
+Usage: ${0##*/} [options] [DOC_RESOURCE]
+Fetch triples from the LOD Cloud, using data hosted and cleaned by the LOD Laundromat. 
+When a LOD Laundromat resource (DOC_RESOURCE) is passed as parameter, triples are fetched from that document.
+Otherwise, triples are fetched from the complete LOD Cloud
 
-    -h          display this help and exit
-    -f OUTFILE  write the result to OUTFILE instead of standard output.
+    -h
+        display this help and exit
+    -s SUBJECT
+    --subject SUBJECT
+        Filter triples by SUBJECT
+    -p PREDICATE
+    --predicate PREDICATE
+        Filter triples by PREDICATE
+    -o OBJECT
+    --object OBJECT
+        Filter triples by OBJECT
+    -g
+    --showGraph
+        Return quads, where the named graph is the reference to the LOD Laundromat resource 
+        of this particular dataset
+
 EOF
 }
   
-file=
-verbose=0
-
+sub=
+pred=
+obj=
+showGraph=false
 while [ "$#" -gt 0 ]; do
     case $1 in
         -h|-\?|--help)   # Call a "show_help" function to display a synopsis, then exit.
             show_help
             exit
             ;;
-        -f|--file)       # Takes an option argument, ensuring it has been specified.
+        
+        ##parse subject
+        -s|--subject)
             if [ "$#" -gt 1 ]; then
-                file=$2
+                sub=$2
                 shift 2
                 continue
             else
-                echo 'ERROR: Must specify a non-empty "--file FILE" argument.' >&2
+                echo 'ERROR: Must specify a non-empty "--subject SUBJECT" argument.' >&2
                 exit 1
             fi
             ;;
-        --file=?*)
-            file=${1#*=} # Delete everything up to "=" and assign the remainder.
+        --subject=?*)
+            sub=${1#*=} # Delete everything up to "=" and assign the remainder.
             ;;
-        --file=)         # Handle the case of an empty --file=
-            echo 'ERROR: Must specify a non-empty "--file FILE" argument.' >&2
+        --subject=)         # Handle the case of an empty --file=
+            echo 'ERROR: Must specify a non-empty "--subject SUBJECT" argument.' >&2
             exit 1
             ;;
-        -v|--verbose)
-            verbose=$((verbose + 1)) # Each -v argument adds 1 to verbosity.
+            
+        ##parse predicate
+        -p|--predicate)
+            if [ "$#" -gt 1 ]; then
+                pred=$2
+                shift 2
+                continue
+            else
+                echo 'ERROR: Must specify a non-empty "--predicate PREDICATE" argument.' >&2
+                exit 1
+            fi
+            ;;
+        --predicate=?*)
+            pred=${1#*=} # Delete everything up to "=" and assign the remainder.
+            ;;
+        --predicate=)         # Handle the case of an empty --file=
+            echo 'ERROR: Must specify a non-empty "--predicate PREDICATE" argument.' >&2
+            exit 1
+            ;;
+            
+         ##parse object
+        -o|--object)
+            if [ "$#" -gt 1 ]; then
+                obj=$2
+                shift 2
+                continue
+            else
+                echo 'ERROR: Must specify a non-empty "--object OBJECT" argument.' >&2
+                exit 1
+            fi
+            ;;
+        --object=?*)
+            obj=${1#*=} # Delete everything up to "=" and assign the remainder.
+            ;;
+        --object=)         # Handle the case of an empty --file=
+            echo 'ERROR: Must specify a non-empty "--object OBJECT" argument.' >&2
+            exit 1
+            ;;
+            
+            
+       
+        -g|--showGraph)
+            showGraph=true;
             ;;
         --)              # End of all options.
             shift
@@ -61,8 +120,64 @@ while [ "$#" -gt 0 ]; do
     shift
 done
 
-# Suppose --file is a required option. Check that it has been set.
-if [ ! "$file" ]; then
-    echo 'ERROR: option "--file FILE" not given. See --help.' >&2
-    exit 1
+##
+## Tricky way of detecting which directory
+##
+SOURCE="${BASH_SOURCE[0]}"
+while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
+  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+  SOURCE="$(readlink "$SOURCE")"
+  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
+done
+dirOfFile="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+
+frankDocs=
+if command -v frankDocuments > /dev/null 2> /dev/null; then
+    frankDocs="frankDocuments"
+else
+    #try to see whether this script exists in the current directory
+    DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+    if command -v $DIR/frankDocuments > /dev/null 2> /dev/null; then
+        frankDocs=$DIR/frankDocuments
+    else
+        echo "ERROR: could not detect frankDocuments script. Either add it to your PATH environment variable, or include it next to this script"
+        exit 1
+    fi 
 fi
+
+
+
+
+
+
+
+ldfApi="http://ldf.lodlaundromat.org"
+while read doc; do 
+    quadReplace=$(echo "$doc" | sed -e 's/[\/&]/\\&/g')
+    md5=$(echo "$doc" | sed 's/.*\/\([a-z0-9]\{32\}\).*/\1/')
+    url="$ldfApi/$md5"
+    
+    #while we have something to send request to, i.e. pagination has not finished yet for this document
+    while [ -n "$url" ]; do
+        
+        response=$(curl -Gs $url -H "Accept: application/n-quads" --data-urlencode "subject=$sub" --data-urlencode "predicate=$pred" --data-urlencode "object=$obj")
+        url=
+        while read quad; do
+            if echo $quad | grep -qE '#metadata>\s*\.'; then
+                if echo $quad | grep -q 'nextPage'; then
+                    url=$(echo "$quad" | sed 's/.*nextPage>\s*<\(.*\)>\s*<.*/\1/')
+                fi
+            else 
+                if $showGraph ; then
+                    echo "$quad" | sed "s/\(.*\)\.$/\1 <$quadReplace>./"
+                    exit;
+                else
+                    echo $quad;
+                fi
+            fi
+            
+        done <<< "$response"
+    done;
+#done < <(test -z $graph -a echo $graph || $frankDocs -r)
+done < <( $frankDocs -r)
+#or loop through $@ (remaining args)
